### ISSUE TITLE
pom for xjoin

### ISSUE THREAD

**Issue by lianyi** [flaxsearch/BioSolr#1]
Would it possible to have a maven pom, or perhaps something equivalent for building the xjoin code?

I was looking at the code under /sequence and seems missing the dependency from package  uk.ac.ebi.webservices.axis1.stubs.fasta, and javax.json.

**Comment by tomjon** [comment]
Hi, if you want to start using XJoin for your SOLR project then the best way is to download a patch from https://issues.apache.org/jira/browse/SOLR-7341 - if you do, let me know how that goes. What version are you using?

If you really do want the FASTA implementation, too, then that's accessible via the EBI's confluence, or else I can send you the relevant packages.

**Comment by lianyi** [comment]
Thanks @tomjon ! The patch worked nicely. Not ready to dive into the FASTA implementation yet but I'm thinking it might be very convenient to have a generic factoryClass for xjoin that able to retrieve external UIDs by http request(json/csv/xml).

**Comment by tomjon** [comment]
Excellent. The FASTA implementation is just for a particular genetic
similarity algorithm.  Your project sounds interesting..

On 9 November 2015 at 20:14, Lianyi <notifications@github.com> wrote:

> Thanks @tomjon <https://github.com/tomjon> ! The patch worked nicely. Not
> ready to dive into the FASTA implementation yet but I'm thinking it might
> be very convenient to have a generic factoryClass for xjoin that able to
> retrieve external UIDs by http request(json/csv/xml).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flaxsearch/BioSolr/issues/1#issuecomment-155178145>.
>



-- 
Tom Winch
Flax
tomw@flax.co.uk

**Comment by lianyi** [comment]
Thanks AGN, closing the issue
